//
//  STMessages.swift
//  STChatViewController
//
//  Created by Creatrixe on 30/03/2019.
//  Copyright © 2019 Creatrixe. All rights reserved.
//

import Foundation
import UIKit
class STMessage: NSObject{
    var sender: String!
    var time: Int!
    var message: String!
    var messageType: String!
    var picture: UIImage?
    public static var dummyMessages = [STMessage]()
    
    init(sender: String, time: Int, message: String, messageType: String = "text", picture: UIImage?) {
        self.sender = sender
        self.time = time
        self.message = message
        self.messageType = messageType
        self.picture = picture
    }
    
    public static func loadDummyMessages(){
        dummyMessages = []
        dummyMessages.append(STMessage(sender: "1", time: 1234567, message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nibh diam, iaculis vitae venenatis vel, vestibulum ac augue. In porttitor quam vitae consectetur faucibus. Vivamus finibus purus in tellus hendrerit rutrum. Phasellus arcu metus, sodales id tellus eget, consequat tempus ex. Mauris nec dolor laoreet, mollis odio et, consequat tellus. Donec magna arcu, finibus at consequat quis, rhoncus a eros. Ut et fringilla dolor, varius semper nibh. Morbi enim justo, venenatis ut faucibus a, placerat a ipsum. Maecenas imperdiet non nulla et facilisis. Donec vel ligula pretium, vulputate lacus sit amet, maximus sapien.", picture: nil))
        dummyMessages.append(STMessage(sender: "2", time: 1234567, message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nibh diam, iaculis vitae venenatis vel, vestibulum ac augue. In porttitor quam vitae consectetur faucibus. Vivamus finibus purus in tellus hendrerit rutrum. Phasellus arcu metus, sodales id tellus eget, consequat tempus ex. Mauris nec dolor laoreet, mollis odio et, consequat tellus. Donec magna arcu, finibus at consequat quis, rhoncus a eros. Ut et fringilla dolor, varius semper nibh. Morbi enim justo, venenatis ut faucibus a, placerat a ipsum. Maecenas imperdiet non nulla et facilisis. Donec vel ligula pretium, vulputate lacus sit amet, maximus sapien.", picture: nil))
        dummyMessages.append(STMessage(sender: "1", time: 1234567, message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nibh diam, iaculis vitae venenatis vel, vestibulum ac augue. In porttitor quam vitae consectetur faucibus. Vivamus finibus purus in tellus hendrerit rutrum. Phasellus arcu metus, sodales id tellus eget, consequat tempus ex. Mauris nec dolor laoreet, mollis odio et, consequat tellus. Donec magna arcu, finibus at consequat quis, rhoncus a eros. Ut et fringilla dolor, varius semper nibh. Morbi enim justo, venenatis ut faucibus a, placerat a ipsum. Maecenas imperdiet non nulla et facilisis. Donec vel ligula pretium, vulputate lacus sit amet, maximus sapien.", picture: nil))
        dummyMessages.append(STMessage(sender: "2", time: 1234567, message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nibh diam, iaculis vitae venenatis vel, vestibulum ac augue. In porttitor quam vitae consectetur faucibus. Vivamus finibus purus in tellus hendrerit rutrum. Phasellus arcu metus, sodales id tellus eget, consequat tempus ex. Mauris nec dolor laoreet, mollis odio et, consequat tellus. Donec magna arcu, finibus at consequat quis, rhoncus a eros. Ut et fringilla dolor, varius semper nibh. Morbi enim justo, venenatis ut faucibus a, placerat a ipsum. Maecenas imperdiet non nulla et facilisis. Donec vel ligula pretium, vulputate lacus sit amet, maximus sapien.", picture: nil))
        dummyMessages.append(STMessage(sender: "2", time: 1234567, message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nibh diam, iaculis vitae venenatis vel, vestibulum ac augue. In porttitor quam vitae consectetur faucibus. Vivamus finibus purus in tellus hendrerit rutrum. Phasellus arcu metus, sodales id tellus eget, consequat tempus ex. Mauris nec dolor laoreet, mollis odio et, consequat tellus. Donec magna arcu, finibus at consequat quis, rhoncus a eros. Ut et fringilla dolor, varius semper nibh. Morbi enim justo, venenatis ut faucibus a, placerat a ipsum. Maecenas imperdiet non nulla et facilisis. Donec vel ligula pretium, vulputate lacus sit amet, maximus sapien.", picture: nil))
        dummyMessages.append(STMessage(sender: "1", time: 1234567, message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nibh diam, iaculis vitae venenatis vel, vestibulum ac augue. In porttitor quam vitae consectetur faucibus. Vivamus finibus purus in tellus hendrerit rutrum. Phasellus arcu metus, sodales id tellus eget, consequat tempus ex. Mauris nec dolor laoreet, mollis odio et, consequat tellus. Donec magna arcu, finibus at consequat quis, rhoncus a eros. Ut et fringilla dolor, varius semper nibh. Morbi enim justo, venenatis ut faucibus a, placerat a ipsum. Maecenas imperdiet non nulla et facilisis. Donec vel ligula pretium, vulputate lacus sit amet, maximus sapien.", picture: nil))
        dummyMessages.append(STMessage(sender: "2", time: 1234567, message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nibh diam, iaculis vitae venenatis vel, vestibulum ac augue. In porttitor quam vitae consectetur faucibus. Vivamus finibus purus in tellus hendrerit rutrum. Phasellus arcu metus, sodales id tellus eget, consequat tempus ex. Mauris nec dolor laoreet, mollis odio et, consequat tellus. Donec magna arcu, finibus at consequat quis, rhoncus a eros. Ut et fringilla dolor, varius semper nibh. Morbi enim justo, venenatis ut faucibus a, placerat a ipsum. Maecenas imperdiet non nulla et facilisis. Donec vel ligula pretium, vulputate lacus sit amet, maximus sapien.", picture: nil))
        dummyMessages.append(STMessage(sender: "1", time: 1234567, message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nibh diam, iaculis vitae venenatis vel, vestibulum ac augue. In porttitor quam vitae consectetur faucibus. Vivamus finibus purus in tellus hendrerit rutrum. Phasellus arcu metus, sodales id tellus eget, consequat tempus ex. Mauris nec dolor laoreet, mollis odio et, consequat tellus. Donec magna arcu, finibus at consequat quis, rhoncus a eros. Ut et fringilla dolor, varius semper nibh. Morbi enim justo, venenatis ut faucibus a, placerat a ipsum. Maecenas imperdiet non nulla et facilisis. Donec vel ligula pretium, vulputate lacus sit amet, maximus sapien.", picture: nil))
        dummyMessages.append(STMessage(sender: "2", time: 1234567, message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nibh diam, iaculis vitae venenatis vel, vestibulum ac augue. In porttitor quam vitae consectetur faucibus. Vivamus finibus purus in tellus hendrerit rutrum. Phasellus arcu metus, sodales id tellus eget, consequat tempus ex. Mauris nec dolor laoreet, mollis odio et, consequat tellus. Donec magna arcu, finibus at consequat quis, rhoncus a eros. Ut et fringilla dolor, varius semper nibh. Morbi enim justo, venenatis ut faucibus a, placerat a ipsum. Maecenas imperdiet non nulla et facilisis. Donec vel ligula pretium, vulputate lacus sit amet, maximus sapien.", picture: nil))
        dummyMessages.append(STMessage(sender: "1", time: 1234567, message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nibh diam, iaculis vitae venenatis vel, vestibulum ac augue. In porttitor quam vitae consectetur faucibus. Vivamus finibus purus in tellus hendrerit rutrum. Phasellus arcu metus, sodales id tellus eget, consequat tempus ex. Mauris nec dolor laoreet, mollis odio et, consequat tellus. Donec magna arcu, finibus at consequat quis, rhoncus a eros. Ut et fringilla dolor, varius semper nibh. Morbi enim justo, venenatis ut faucibus a, placerat a ipsum. Maecenas imperdiet non nulla et facilisis. Donec vel ligula pretium, vulputate lacus sit amet, maximus sapien.", picture: nil))
        dummyMessages.append(STMessage(sender: "2", time: 1234567, message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nibh diam, iaculis vitae venenatis vel, vestibulum ac augue. In porttitor quam vitae consectetur faucibus. Vivamus finibus purus in tellus hendrerit rutrum. Phasellus arcu metus, sodales id tellus eget, consequat tempus ex. Mauris nec dolor laoreet, mollis odio et, consequat tellus. Donec magna arcu, finibus at consequat quis, rhoncus a eros. Ut et fringilla dolor, varius semper nibh. Morbi enim justo, venenatis ut faucibus a, placerat a ipsum. Maecenas imperdiet non nulla et facilisis. Donec vel ligula pretium, vulputate lacus sit amet, maximus sapien.", picture: nil))
        dummyMessages.append(STMessage(sender: "1", time: 1234567, message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nibh diam, iaculis vitae venenatis vel, vestibulum ac augue. In porttitor quam vitae consectetur faucibus. Vivamus finibus purus in tellus hendrerit rutrum. Phasellus arcu metus, sodales id tellus eget, consequat tempus ex. Mauris nec dolor laoreet, mollis odio et, consequat tellus. Donec magna arcu, finibus at consequat quis, rhoncus a eros. Ut et fringilla dolor, varius semper nibh. Morbi enim justo, venenatis ut faucibus a, placerat a ipsum. Maecenas imperdiet non nulla et facilisis. Donec vel ligula pretium, vulputate lacus sit amet, maximus sapien.", picture: nil))
        dummyMessages.append(STMessage(sender: "2", time: 1234567, message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nibh diam, iaculis vitae venenatis vel, vestibulum ac augue. In porttitor quam vitae consectetur faucibus. Vivamus finibus purus in tellus hendrerit rutrum. Phasellus arcu metus, sodales id tellus eget, consequat tempus ex. Mauris nec dolor laoreet, mollis odio et, consequat tellus. Donec magna arcu, finibus at consequat quis, rhoncus a eros. Ut et fringilla dolor, varius semper nibh. Morbi enim justo, venenatis ut faucibus a, placerat a ipsum. Maecenas imperdiet non nulla et facilisis. Donec vel ligula pretium, vulputate lacus sit amet, maximus sapien.", picture: nil))
        dummyMessages.append(STMessage(sender: "1", time: 1234567, message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nibh diam, iaculis vitae venenatis vel, vestibulum ac augue. In porttitor quam vitae consectetur faucibus. Vivamus finibus purus in tellus hendrerit rutrum. Phasellus arcu metus, sodales id tellus eget, consequat tempus ex. Mauris nec dolor laoreet, mollis odio et, consequat tellus. Donec magna arcu, finibus at consequat quis, rhoncus a eros. Ut et fringilla dolor, varius semper nibh. Morbi enim justo, venenatis ut faucibus a, placerat a ipsum. Maecenas imperdiet non nulla et facilisis. Donec vel ligula pretium, vulputate lacus sit amet, maximus sapien.", picture: nil))
        dummyMessages.append(STMessage(sender: "2", time: 1234567, message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nibh diam, iaculis vitae venenatis vel, vestibulum ac augue. In porttitor quam vitae consectetur faucibus. Vivamus finibus purus in tellus hendrerit rutrum. Phasellus arcu metus, sodales id tellus eget, consequat tempus ex. Mauris nec dolor laoreet, mollis odio et, consequat tellus. Donec magna arcu, finibus at consequat quis, rhoncus a eros. Ut et fringilla dolor, varius semper nibh. Morbi enim justo, venenatis ut faucibus a, placerat a ipsum. Maecenas imperdiet non nulla et facilisis. Donec vel ligula pretium, vulputate lacus sit amet, maximus sapien.", picture: nil))
        dummyMessages.append(STMessage(sender: "1", time: 1234567, message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nibh diam, iaculis vitae venenatis vel, vestibulum ac augue. In porttitor quam vitae consectetur faucibus. Vivamus finibus purus in tellus hendrerit rutrum. Phasellus arcu metus, sodales id tellus eget, consequat tempus ex. Mauris nec dolor laoreet, mollis odio et, consequat tellus. Donec magna arcu, finibus at consequat quis, rhoncus a eros. Ut et fringilla dolor, varius semper nibh. Morbi enim justo, venenatis ut faucibus a, placerat a ipsum. Maecenas imperdiet non nulla et facilisis. Donec vel ligula pretium, vulputate lacus sit amet, maximus sapien.", picture: nil))
        dummyMessages.append(STMessage(sender: "2", time: 1234567, message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nibh diam, iaculis vitae venenatis vel, vestibulum ac augue. In porttitor quam vitae consectetur faucibus. Vivamus finibus purus in tellus hendrerit rutrum. Phasellus arcu metus, sodales id tellus eget, consequat tempus ex. Mauris nec dolor laoreet, mollis odio et, consequat tellus. Donec magna arcu, finibus at consequat quis, rhoncus a eros. Ut et fringilla dolor, varius semper nibh. Morbi enim justo, venenatis ut faucibus a, placerat a ipsum. Maecenas imperdiet non nulla et facilisis. Donec vel ligula pretium, vulputate lacus sit amet, maximus sapien.", picture: nil))
    }
}
